/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.HotelDAO;
import Controlador.ProveedorDAO;
import Controlador.SuministroDAO;
import Model.Proveedor;
import Model.Restaurante;
import Model.Suministro;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tesci
 */
public class VistaSuministro extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
    private SuministroDAO suministroDAO;
    private ProveedorDAO proveedorDAO;
    private HotelDAO hoteles;

    /**
     * Creates new form VistaSuministro
     */
    public VistaSuministro() {
        suministroDAO = new SuministroDAO();
        hoteles= new HotelDAO();
        proveedorDAO= new ProveedorDAO();
        initComponents();
        actualizarComboBoxConModelo();
        actualizarComboBoxConModelo2();
        mostrarSumistroEnTabla();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("GESTION DE SUMINISTRO");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripcion");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Precio Unitario");

        jLabel6.setText("Proveedor");

        jLabel7.setText("Hotel");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4)
                            .addComponent(jComboBox1, 0, 203, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jButton5))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
crearSuministro();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
modificarSuministro();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

          int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
        try {
            Object objRestaurante = model.getValueAt(filaSeleccionada, 0);  // 0 es el índice de la primera columna
            int idSuministro = Integer.parseInt(objRestaurante.toString());
                List<Suministro> restaurantes = suministroDAO.obtenerSuministrosBuscar(idSuministro);
                for (Suministro restaurante : restaurantes) {
                jTextField1.setText(restaurante.getNombre());
                jTextField2.setText(restaurante.getDescripcion());
                jTextField3.setText(restaurante.getCantidad()+"");
                jTextField4.setText(restaurante.getPrecioUnitario()+"");
            }
            Mostrar(); // Actualiza la lista después de modificar
        } catch (Exception e) {
            e.printStackTrace();
        }
        }else {
    JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna ID DE LA TABLA.");
}
        
        
        
   

      
            
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       eliminarSuministro(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Menu mens=new Menu();
mens.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSuministro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSuministro().setVisible(true);
            }
        });
    }
    public void Mostrar(){
       try {
               DefaultTableModel model = new DefaultTableModel();

            // Crear modelo de tabla
            model.addColumn("ID Suministro");
            model.addColumn("Nombre");
            model.addColumn("Descripción");
            model.addColumn("Cantidad");
            model.addColumn("Precio Unitario");
            model.addColumn("ID Proveedor");
            model.addColumn("ID Hotel");
            
            // Obtener los proveedores y agregar filas
            List<Suministro> suministro = suministroDAO.obtenerSuministros();
            for (Suministro suministros : suministro) {
                model.addRow(new Object[]{
                    suministros.getIdSuministro(),
                    suministros.getNombre(),
                    suministros.getDescripcion(),
                    suministros.getCantidad(),
                    suministros.getPrecioUnitario(),
                    suministros.getIdProveedor(),
                    suministros.getIdHotel()
                });
            }
            
            // Asignar el modelo a la tabla
            jTable1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(VistaSuministro.class.getName()).log(Level.SEVERE, null, ex);
        }
}
public void actualizarComboBoxConModelo() {
    try {
        // Obtener la lista de hoteles
        List<String> hotels = hoteles.obtenerHoteles();

        // Crear un modelo para el JComboBox
   
        // Agregar los elementos al modelo
        for (int i = 0; i < hotels.size(); i++) {
           jComboBox2.addItem( hotels.get(i));
  }

        // Asignar el modelo al JComboBox
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar hoteles: " + e.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
}
public void actualizarComboBoxConModelo2() {
    try {
        // Obtener la lista de hoteles
        List<String> hotels = proveedorDAO.obtenerProveedoresporNombre();

        // Crear un modelo para el JComboBox
   
        // Agregar los elementos al modelo
        for (int i = 0; i < hotels.size(); i++) {
           jComboBox1.addItem( hotels.get(i));
  }

        // Asignar el modelo al JComboBox
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al cargar hoteles: " + e.getMessage(),
                                      "Error", JOptionPane.ERROR_MESSAGE);
    }
}
public void mostrarSumistroEnTabla() {
        try {
            // Crear modelo de tabla
            model.addColumn("ID Suministro");
            model.addColumn("Nombre");
            model.addColumn("Descripción");
            model.addColumn("Cantidad");
            model.addColumn("Precio Unitario");
            model.addColumn("ID Proveedor");
            model.addColumn("ID Hotel");
            
            // Obtener los proveedores y agregar filas
            List<Suministro> suministro = suministroDAO.obtenerSuministros();
            for (Suministro suministros : suministro) {
                model.addRow(new Object[]{
                    suministros.getIdSuministro(),
                    suministros.getNombre(),
                    suministros.getDescripcion(),
                    suministros.getCantidad(),
                    suministros.getPrecioUnitario(),
                    suministros.getIdProveedor(),
                    suministros.getIdHotel()
                });
            }
            
            // Asignar el modelo a la tabla
            jTable1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(VistaSuministro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void crearSuministro() {
        try {
            int idho=hoteles.obtenerIdHotelPorNombre((String)jComboBox2.getSelectedItem());
            int idproveed=proveedorDAO.obtenerIdProveedorPorNombre((String)jComboBox1.getSelectedItem());
            Suministro suministro = new Suministro(
                    0, jTextField1.getText(), jTextField2.getText(),
                    Integer.parseInt(jTextField3.getText()), Double.parseDouble(jTextField4.getText()),
                    idproveed, idho
            );
            suministroDAO.crearSuministro(suministro);
            Mostrar();
            // Actualiza la lista después de crear
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
private void modificarSuministro() {
    
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada != -1) {
        try {
             int idho=hoteles.obtenerIdHotelPorNombre((String)jComboBox2.getSelectedItem());
            int idproveed=proveedorDAO.obtenerIdProveedorPorNombre((String)jComboBox1.getSelectedItem());
            Object objRestaurante = model.getValueAt(filaSeleccionada, 0);  // 0 es el índice de la primera columna
            int idSuministro = Integer.parseInt(objRestaurante.toString());
            Suministro suministro = new Suministro(
                    Integer.parseInt(jTextField3.getText()), jTextField1.getText(), jTextField2.getText(),
                    Integer.parseInt(jTextField3.getText()), Double.parseDouble(jTextField4.getText()),
                    idproveed, idho
            );
            suministroDAO.modificarSuministro(suministro, idSuministro);
            Mostrar(); // Actualiza la lista después de modificar
        } catch (Exception e) {
            e.printStackTrace();
        }
        }else {
    JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna ID DE LA TABLA.");
}
    }
 private void eliminarSuministro() {
        try {
            int idSuministro = Integer.parseInt(JOptionPane.showInputDialog(null, "Escribe el código de identificador"));
            suministroDAO.eliminarSuministro(idSuministro);
            Mostrar(); // Actualiza la lista después de eliminar
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
